"""empty message

Revision ID: 16fb44670bd8
Revises: 802e45a67c36
Create Date: 2016-10-25 02:57:11.583438

"""

# revision identifiers, used by Alembic.
revision = '16fb44670bd8'
down_revision = '802e45a67c36'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=True),
    sa.Column('created_time', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('weibo_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weibos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=True),
    sa.Column('created_time', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weibos')
    op.drop_table('comments')
    ### end Alembic commands ###
